name: ci

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dotnet-install
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: dotnet-restore
      run: dotnet restore
    - name: dotnet-build
      run: dotnet build -c Release --no-restore
    - name: dotnet-test
      run: dotnet test -c Release -p:CollectCoverage=true -p:CoverletOutput=coverage-results/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal
    - name: upload-coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: Test/coverage-results/coverage.opencover.xml
        verbose: true
